@startuml
'https://plantuml.com/class-diagram


interface Comparator <<interface>>

class Client{
+ void sort(T[] arr, Comparator<T> c)
}

class ObjectCompareByWeight{}
class ObjectCompareByHeight{}
class ObjectCompareByAge{}

Client - Comparator

Comparator <|-- ObjectCompareByWeight
Comparator <|-- ObjectCompareByHeight
Comparator <|-- ObjectCompareByAge

@enduml