@startuml
'https://plantuml.com/class-diagram

class client{
    State stat
    Operation() -> stat.handle()
}

abstract class State {
    + handle()
}

client::stat o-- State


class ConcreteState1{
    + handle()
}

class ConcreteState2{
    + handle()
}

class ConcreteState3{
    + handle()
}

State <|-- ConcreteState1
State <|-- ConcreteState2
State <|-- ConcreteState3

@enduml